### ISSUE TITLE
ENH: add MaxBin2 as another binning option

### ISSUE THREAD

**Issue by misialq** [bokulich-lab/q2-moshpit#77]
**Describe the solution you'd like**
I'd like another action (`bin-contigs-maxbin2`) which can take contigs as input (plus whatever else that is required) and use MaxBin2 to produce bins, similarly to how `bin-contigs-metabat` does.

**Describe alternatives you've considered**
- https://github.com/BinPro/CONCOCT: few years older, can't install due to Python pin (<3.7)
- https://github.com/ziyewang/MetaBinner: looks interesting but Python is pinned to 3.7

**Additional context**
There is very little documentation available... Basically, just those links may be of help:
- [installation](https://sourceforge.net/projects/maxbin/)
- [Nextflow module showing usage](https://github.com/nf-core/mag/blob/master/modules/nf-core/maxbin2/main.nf)
- [paper](https://academic.oup.com/bioinformatics/article/32/4/605/1744462)
- [protocol description](https://currentprotocols.onlinelibrary.wiley.com/doi/full/10.1002/cpz1.128)
- copy of the help entry from the tool itself:
```
MaxBin 2.2.7
No Contig file. Please specify contig file by -contig
MaxBin - a metagenomics binning software.
Usage:
  run_MaxBin.pl
    -contig (contig file)
    -out (output file)

   (Input reads and abundance information)
    [-reads (reads file) -reads2 (readsfile) -reads3 (readsfile) -reads4 ... ]
    [-abund (abundance file) -abund2 (abundfile) -abund3 (abundfile) -abund4 ... ]

   (You can also input lists consisting of reads and abundance files)
    [-reads_list (list of reads files)]
    [-abund_list (list of abundance files)]

   (Other parameters)
    [-min_contig_length (minimum contig length. Default 1000)]
    [-max_iteration (maximum Expectation-Maximization algorithm iteration number. Default 50)]
    [-thread (thread num; default 1)]
    [-prob_threshold (probability threshold for EM final classification. Default 0.9)]
    [-plotmarker]
    [-markerset (marker gene sets, 107 (default) or 40.  See README for more information.)]

  (for debug purpose)
    [-version] [-v] (print version number)
    [-verbose]
    [-preserve_intermediate]

  Please specify either -reads or -abund information.
  You can input multiple reads and/or abundance files at the same time.
  Please read README file for more details.
```

**Comment by Sann5** [comment]
### MaxBin incompatible with Mac

- The installation of the required dependencies is not successful. However, enough is installed to run some of the protocols from the maintainers [protocol publication].(https://currentprotocols.onlinelibrary.wiley.com/doi/full/10.1002/cpz1.128)
- Specifically, I tried running ["Basic Protocol 2"](https://currentprotocols.onlinelibrary.wiley.com/doi/full/10.1002/cpz1.128#:~:text=out%2080X.out-,Basic%20Protocol%202%3A%20RECOVERING%20GENOMES%20FROM%20ONE%20SHOTGUN%20METAGENOME%20WITHOUT%20COVERAGE%20INFORMATION,-Basic%20Protocol) and obtained the following error:
```
Running FragGeneScan....
Error running FragGeneScan. Output recorded in s44.contig.tmp.frag.out and s44.contig.tmp.frag.err.
=== Please make sure that you are running FragGeneScan 1.18 or above. ===
=== There are known bugs in v1.17 and before that will crash FragGeneScan program. ===
```
- The source of the issue is that "the auxiliary software FragGeneScan cannot make it to Mac" as pointed out in this [issue](https://sourceforge.net/p/maxbin/tickets/2/#:~:text=2019%2D05%2D29-,Hi.%20I%20just%20noticed%20that%20there%20are%20tickets%20on%20Souceforge.%20Sorry,that%20it%20should%20work%20well%20on%20most%20Linux%20machine.%20Thank%20you,-.) posted on MaxBin's Souceforge page. 
- Finally, the maintainers also point out in their [protocol publication](https://currentprotocols.onlinelibrary.wiley.com/doi/full/10.1002/cpz1.128#:~:text=Currently%2C%20MaxBin%20does%20not%20support%20Macintosh%20machines%20and%20operating%20systems.) that "MaxBin does not support Macintosh machines and operating systems".
